select * from public.user;

insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (2, 'Leora', 'Mélinda', 'Skures', 2421729167, 60241, 'Bashford', 'Shuangjie', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (3, 'Germain', 'Yénora', 'Dufaire', 2171499154, 1417, 'Evergreen', 'Muli', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (4, 'Aylmar', 'Félicie', 'Louw', 2431434809, 2428, 'Oak', 'Dunkerque', 'Nord-Pas-de-Calais');
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (5, 'Martyn', 'Tán', 'Brea', 2055131867, 524, 'Veith', 'Raydah', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (6, 'Merv', 'Ruì', 'Housecraft', 5163822178, 855, 'Fieldstone', 'Hongling', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (7, 'Angus', 'Lài', 'Jalland', 2297153486, 045, 'Reinke', 'Koloniya Zastav’ye', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (8, 'Ezechiel', 'Marie-thérèse', 'Tomisch', 3371199055, 60, 'American Ash', 'Stulovo', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (9, 'Brittne', 'Andrée', 'Costa', 9526653615, 64, 'Shelley', 'Pagelaran', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (10, 'Emera', 'Yóu', 'Droghan', 4529102387, 396, 'Northland', 'Al Ghizlānīyah', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (11, 'Isaiah', 'Marie-josée', 'Bee', 4637546814, 21, 'Fulton', 'Port Louis', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (12, 'Jameson', 'Mén', 'Vigars', 4774209259, 3, 'Katie', 'Kiraman', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (13, 'Clemmy', 'Cléopatre', 'Stiggers', 6852561162, 0577, 'Dryden', 'Székesfehérvár', 'Fejér');
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (14, 'Thomasina', 'Vérane', 'Adne', 6951562987, 1, 'Charing Cross', 'Vila Boa do Bispo', 'Porto');
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (15, 'Elbertina', 'Marlène', 'Cobb', 2768851855, 890, 'Golden Leaf', 'Yashiga', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (16, 'Edith', 'Maëlla', 'Lorenzetto', 2028124694, 30, 'Southridge', 'Araçatuba', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (17, 'Andy', 'Maëlys', 'Roseblade', 2374546193, 227, 'Nobel', 'Pirapora', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (18, 'Torin', 'Adèle', 'Bobasch', 9515998489, 03, 'Ridge Oak', 'Verkhniy Avzyan', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (19, 'Mufinella', 'Béatrice', 'Boich', 6253626705, 84, 'Hanson', 'Suvorovskaya', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (20, 'Kathy', 'Félicie', 'Lammertz', 9749162898,1, 'Macpherson', 'Dengfeng', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (21, 'Lucine', 'Åsa', 'McLanaghan', 7223703026, 19, 'Grim', 'Hetou', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (22, 'Leeann', 'Nadège', 'Jiru', 2752788667, 7, 'Rigney', 'Saint-Eustache', 'Québec');
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (23, 'Gerrie', 'Laurène', 'Jezard', 8558589583, 2618, 'Debra', 'Suya', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (24, 'Corrianne', 'Bénédicte', 'Brusin', 5879415360, 5, 'Burrows', 'Xinxikou', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (25, 'Shawn', 'Anaëlle', 'Conichie', 7414056582, 499, 'Melvin', 'Iporá', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (26, 'Matthus', 'Rachèle', 'Durrand', 6715387835, 7, 'Northport', 'Halat', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (27, 'Suki', 'Régine', 'Brugh', 1276938822, 753, 'Waxwing', 'Ambato Boeny', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (28, 'Shanie', 'Bécassine', 'Alkins', 6584745200, 9010, 'Farmco', 'Alpatovo', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (29, 'Ingmar', 'Måns', 'Dunge', 6334042332, 3, 'Bellgrove', 'Ropa', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (30, 'Georgiana', 'Séverine', 'Crebo', 7948759084, 8237, 'Saint Paul', 'Pyshchug', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (31, 'Brett', 'Björn', 'Welling', 1548997851, 92, 'Oak', 'Dębe Wielkie', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (32, 'Carmel', 'Célestine', 'Braunfeld', 1623746826, 9225, 'Westerfield', 'Banjiang', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (33, 'Gussy', 'Mélys', 'Newart', 4114331527, 067, 'Mcguire', 'Lukou', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (34, 'Freida', 'Marie-thérèse', 'Mc Ilwrick', 9947657517, 3, 'Kropf', 'Shuangjie', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (35, 'Luz', 'Geneviève', 'Eeles', 3772394894, 77438, 'Pankratz', 'Jinqiao', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (36, 'Ozzie', 'Eléonore', 'Selliman', 2788664127, 853, 'Darwin', 'Nyimba', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (37, 'Raimondo', 'Maëly', 'Tuckwood', 6469224043, 7, 'American Ash', 'Chuzhou', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (38, 'Nicolas', 'Alizée', 'Tripony', 9256339169, 05, 'Vahlen', 'Polevskoy', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (39, 'Esme', 'Kù', 'Cockings', 4185917272, 17550, 'Hoffman', 'Awar-awar', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (40, 'Julie', 'Mélinda', 'Carey', 7225890905, 3, 'Carberry', 'Berlin', 'Berlin');
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (41, 'Hervey', 'Zoé', 'Dawidowitsch', 7831889588, 5553, 'Declaration', 'Haoraoshan', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (42, 'Modesty', 'Mélys', 'Pymar', 4275223557, 4, 'Bobwhite', 'Neochórion', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (43, 'Hobart', 'Örjan', 'Allans', 3684974786, 49, 'Shopko', 'Burgastai', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (44, 'Nikoletta', 'Inès', 'Tiebe', 6871048235, 74036, 'Carpenter', 'Xiangang', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (45, 'Marie-jeanne', 'Léane', 'Marjoribanks', 1265105133, 64520, 'Melrose', 'Không', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (46, 'Kippie', 'Maï', 'Kunath', 2432803994, 42, 'Maywood', 'Al Ḩammāmāt', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (47, 'Marty', 'Agnès', 'Oakhill', 5766214591, 04862, 'Lotheville', 'Shilong', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (48, 'Amalie', 'Océanne', 'Lynett', 3081883015, 936, 'Pearson', 'Fontana', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (49, 'Jerry', 'Andréa', 'Martineau', 9639712731, 4, 'Vahlen', 'Bofuer', null);
insert into public.User (id, firstName, middleName, lastName, phoneNumber, address, streetName, city, province) values (50, 'Brady', 'Chloé', 'Grene', 1676518926, 9696, 'Petterle', 'San Pedro Jocopilas', null);
