insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (1, '9', 'Goodland', 'Hōfu', 8.12);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (2, '0', 'Spenser', 'Oujda', 3.78);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (3, '26002', 'Spohn', 'Benito Juarez', 1.5);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (4, '903', 'Green', 'Hongchuan', 0.28);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (5, '7572', 'Continental', 'Černelavci', 7.06);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (6, '4', 'Nova', 'Huangmao', 7.28);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (7, '5806', 'Oriole', 'Weixin', 8.62);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (8, '9961', 'Maple', 'Delmas', 0.42);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (9, '8139', 'Dunning', 'Fada N''gourma', 3.47);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (10, '6416', 'Butterfield', 'Bitung', 7.67);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (11, '7434', 'American Ash', 'eMbalenhle', 6.47);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (12, '6803', 'Columbus', 'Baohe', 2.25);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (13, '065', 'Waxwing', 'Songgang-dong', 8.5);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (14, '948', 'Roth', 'Oslo', 0.94);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (15, '2', 'Pennsylvania', 'Staraya Stanitsa', 1.18);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (16, '33462', 'Forest', 'Amiens', 4.88);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (17, '04976', 'Roth', 'Cachón', 0.66);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (18, '566', 'Pennsylvania', 'Týnec', 1.13);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (19, '98', 'Marquette', 'Pākpattan', 4.16);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (20, '7108', '2nd', 'Jiuting', 7.48);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (21, '37642', 'Granby', 'Yuandianhui', 7.05);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (22, '8101', 'Mayfield', 'Barra de São Francisco', 4.25);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (23, '7', 'Crowley', 'Jiquinlaca', 3.85);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (24, '885', 'Derek', 'Khalopyenichy', 2.65);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (25, '8', 'Armistice', 'Épinal', 8.08);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (26, '231', 'Iowa', 'Manique de Baixo', 1.22);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (27, '09', 'Bultman', 'Gialo', 4.11);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (28, '60424', 'Ridgeview', 'Jiaoshi', 7.13);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (29, '3', 'Cambridge', 'Banqiao', 6.61);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (30, '3504', 'Parkside', 'Barengkok', 7.78);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (31, '1', 'Ridgeview', 'Sztum', 5.24);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (32, '99334', 'Oxford', 'Liushun', 3.76);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (33, '97', 'Mariners Cove', 'Garça', 6.44);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (34, '08612', 'Springview', 'Bua Yai', 3.79);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (35, '4', 'Fordem', 'Issy-les-Moulineaux', 4.68);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (36, '57698', 'Ryan', 'São Miguel de Machede', 1.16);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (37, '61', '5th', 'La Jicaral', 5.04);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (38, '23441', 'Badeau', 'Sicamous', 5.03);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (39, '33', 'Cambridge', 'Kebonagung', 4.68);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (40, '19', 'Loftsgordon', 'Citeureup', 2.57);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (41, '2', 'Ilene', 'Aksu', 7.27);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (42, '45415', 'Welch', 'Nandaime', 7.88);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (43, '6', 'Colorado', 'Guicheng', 6.82);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (44, '0568', 'Mallard', 'Liujiachang', 3.47);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (45, '29', 'Warrior', 'Quime', 1.53);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (46, '7', 'Jay', 'Bueng Sam Phan', 5.95);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (47, '90', 'Eastlawn', 'Wenfeng Zhen', 4.1);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (48, '054', 'Independence', 'Güines', 8.75);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (49, '29304', 'Miller', 'Vecpiebalga', 4.74);
insert into property (ID, streetNumber, streetName, city, proximityToAttractions) values (50, '22525', 'Florence', 'Pajannangger', 2.41);
